export const API = {
    providers_api: {
        get_providers: '/providers/get_providers',
        get_provider_by_id: '/providers/get_provider_by_id',
        create_providers: '/providers/create_providers',
        update_providers: '/providers/update_providers',
        delete_provider: '/providers/delete_provider',
        update_provider_status: '/providers/update_provider_status',
        get_provider_ddl: '/providers/get_provider_ddl',
    },
    game_type_api: {
        get_game_type: '/gametype/get_game_type',
        get_game_type_by_id: '/gametype/get_game_type_by_id',
        create_game_type: '/gametype/create_game_type',
        update_game_type: '/gametype/update_game_type',
        delete_game_type: '/gametype/delete_game_type',
        update_game_type_status: '/gametype/update_game_type_status',
        get_game_type_ddl: '/gametype/get_game_type_ddl',
    },
    device_type_api: {
        get_device_type: '/devicetype/get_device_type',
        get_device_type_by_id: '/devicetype/get_device_type_by_id',
        create_device_type: '/devicetype/create_device_type',
        update_device_type: '/devicetype/update_device_type',
        delete_device_type: '/devicetype/delete_device_type',
        update_device_type_status: '/devicetype/update_device_type_status',
        get_device_type_ddl: '/devicetype/get_device_type_ddl',
    },
    game_category_api: {
        get_game_category: '/gamecategory/get_game_category',
        get_game_category_by_id: '/gamecategory/get_game_category_by_id',
        create_game_category: '/gamecategory/create_game_category',
        update_game_category: '/gamecategory/update_game_category',
        delete_game_category: '/gamecategory/delete_game_category',
        update_game_category_status: '/gamecategory/update_game_category_status',
        get_game_category_ddl: '/gamecategory/get_game_category_ddl',
    },
    games_api: {
        get_games: '/games/get_game',
        get_game_by_id: '/games/get_game_by_id',
        create_game: '/games/create_game',
        update_game: '/games/update_game',
        delete_game: '/games/delete_game',
        update_game_status: '/games/update_game_status',
    },
    dashboard_api: {
        get_statistics: '/dashboard/statistics',
    },
    player_api: {
        get_players: '/player/get_players',
        get_player_by_id: '/player/get_player_by_id',
        create_player: '/player/create_player',
        update_player: '/player/update_player',
        delete_player: '/player/delete_player',
        update_player_status: '/player/update_player_status',
    },
    sport_api: {
        get_sport: '/sport/get_sport',
        get_sport_by_id: '/sport/get_sport_by_id',
        create_sport: '/sport/create_sport',
        update_sport: '/sport/update_sport',
        delete_sport: '/sport/delete_sport',
        update_sport_status: '/sport/update_sport_status',
    }
}